version: '2'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=spiddb
      - POSTGRESQL_USERNAME=spiddb
      - POSTGRESQL_PASSWORD=spiddb
      

volumes:
  postgresql_data:
    driver: local